#![no_main]

//! Fuzz target for MCP tool input parsing
//!
//! This target tests that arbitrary JSON input to tool handlers
//! never causes panics or undefined behavior.

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use serde_json::{Map, Value, json};

use hindsight_mcp::db::Database;
use hindsight_mcp::handlers;

/// Arbitrary tool input that can be generated by the fuzzer
#[derive(Debug, Arbitrary)]
struct ToolInput {
    /// Tool to invoke
    tool_index: u8,
    /// Query string (for search, commit_details)
    query: String,
    /// Limit value (can be negative to test edge cases)
    limit: i64,
    /// Days value (for activity_summary)
    days: i32,
    /// Source value (for search, ingest)
    source: String,
    /// Workspace path
    workspace: String,
    /// SHA string
    sha: String,
    /// Incremental flag (reserved for future ingest testing)
    #[allow(dead_code)]
    incremental: bool,
}

fn create_test_db() -> Database {
    let db = Database::in_memory().expect("create db");
    db.initialize().expect("init db");
    db
}

fn to_map(value: Value) -> Map<String, Value> {
    match value {
        Value::Object(map) => map,
        _ => Map::new(),
    }
}

fuzz_target!(|input: ToolInput| {
    let db = create_test_db();

    // Select tool based on index (mod 5 for 5 read-only tools)
    match input.tool_index % 5 {
        0 => {
            // hindsight_timeline
            let args = to_map(json!({
                "limit": input.limit.max(0).min(10000) as usize,
                "workspace": if input.workspace.is_empty() { None } else { Some(&input.workspace) }
            }));
            let _ = handlers::handle_timeline(&db, Some(args), None);
        }
        1 => {
            // hindsight_search
            let args = to_map(json!({
                "query": &input.query,
                "source": &input.source,
                "limit": input.limit.max(0).min(10000) as usize
            }));
            let _ = handlers::handle_search(&db, Some(args));
        }
        2 => {
            // hindsight_failing_tests
            let args = to_map(json!({
                "limit": input.limit.max(0).min(10000) as usize,
                "workspace": if input.workspace.is_empty() { None } else { Some(&input.workspace) },
                "commit": if input.sha.is_empty() { None } else { Some(&input.sha) }
            }));
            let _ = handlers::handle_failing_tests(&db, Some(args), None);
        }
        3 => {
            // hindsight_activity_summary
            let args = to_map(json!({
                "days": input.days.max(0).min(10000) as u32
            }));
            let _ = handlers::handle_activity_summary(&db, Some(args));
        }
        4 => {
            // hindsight_commit_details
            let args = to_map(json!({
                "sha": &input.sha
            }));
            let _ = handlers::handle_commit_details(&db, Some(args));
        }
        _ => unreachable!(),
    }
});
